In [15]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [17]:
df.shape

(569, 33)

In [18]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [19]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


# Train test split

In [20]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [21]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [22]:
X_train

array([[-0.27629532,  2.01775935, -0.30630783, ..., -0.53847052,
        -0.67152175, -1.09393997],
       [-0.8975103 , -0.1171556 , -0.79793395, ...,  2.17867493,
         2.04077489,  3.24814192],
       [ 1.67192818,  0.21360587,  1.63047834, ...,  0.74636414,
        -0.5488956 ,  0.44727877],
       ...,
       [-0.58252806, -0.30219698, -0.5860847 , ..., -0.89505459,
        -0.77962637, -0.35795508],
       [-1.88591291,  1.41174882, -1.85760477, ..., -1.00353916,
        -0.16004165,  1.31947236],
       [-0.08963918, -0.9614069 , -0.13181877, ..., -0.21851965,
         0.10618615, -0.82552868]], shape=(455, 30))

In [23]:
X_test

array([[ 0.38623244,  0.47235024,  0.42400133, ...,  1.30584555,
         0.092029  ,  0.95840507],
       [-0.26064323,  0.40068678, -0.29506479, ..., -0.74714895,
         0.40875387, -1.05518746],
       [-0.05105551,  1.11015509,  0.00346446, ...,  1.14072169,
         2.43710586,  1.14756827],
       ...,
       [-0.41848089, -0.38761134, -0.40149696, ..., -0.26842623,
        -0.20992631,  1.3068636 ],
       [-0.8143688 ,  0.56790153, -0.85133049, ..., -1.60633889,
        -0.80234951, -0.97703319],
       [ 1.27633335,  0.52729223,  1.19164798, ...,  0.83503785,
        -0.64973079, -0.97852659]], shape=(114, 30))

In [24]:
y_train

543    B
379    M
517    M
190    M
378    B
      ..
11     M
498    M
480    B
539    B
279    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [26]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,

In [27]:
y_test

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1])

# Numpy arrays to PyTorch tensors

In [28]:
X_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [29]:
X_train_tensor.shape

torch.Size([455, 30])

In [30]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [31]:
class MyNN():

    def __init__(self,X):

        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self, X):
        z =torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):

        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

Important parameters

In [32]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [33]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [34]:
# create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
#model.forward(feature)
model(features)

tensor([[0.4363],
        [0.4553],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363]], grad_fn=<SigmoidBackward0>)

In [35]:
#show model weights
model.linear2.weight

Parameter containing:
tensor([[-0.1142,  0.3064,  0.0958]], requires_grad=True)

In [36]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [37]:
# Create a model
model = MyNN(X_train_tensor)

#define loop
for epoch in range(epochs):
# forward bias
  y_pred = model.forward(X_train_tensor)
  print(y_pred)
# loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
#backward bias 
  loss.backward()
#parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
# zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()
# print loss in each epoch
  print('Epoch:' ,{epoch + 1}, 'Loss:' ,{loss.item()})

tensor([[1.2601e-02],
        [9.9995e-01],
        [9.9031e-01],
        [1.0000e+00],
        [6.1902e-03],
        [7.2327e-02],
        [2.2031e-04],
        [7.1229e-01],
        [2.7920e-04],
        [4.1079e-05],
        [6.9145e-01],
        [9.9998e-01],
        [1.0000e+00],
        [2.6983e-02],
        [1.3998e-01],
        [6.4787e-02],
        [2.1415e-03],
        [9.9499e-01],
        [9.9868e-01],
        [1.2091e-02],
        [1.9860e-01],
        [3.1058e-02],
        [9.9492e-01],
        [9.9079e-01],
        [1.5605e-02],
        [9.1168e-01],
        [7.3326e-01],
        [9.9992e-01],
        [9.9999e-01],
        [9.9998e-01],
        [9.9862e-01],
        [1.6234e-04],
        [2.3144e-02],
        [2.0608e-03],
        [3.0320e-03],
        [4.9734e-03],
        [4.1205e-04],
        [2.0194e-04],
        [7.9514e-06],
        [9.9224e-01],
        [9.9774e-01],
        [7.9303e-06],
        [2.1127e-04],
        [9.9982e-01],
        [1.5686e-03],
        [4

In [38]:
model.bias

tensor([-0.1609], dtype=torch.float64, requires_grad=True)