In [95]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [96]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [97]:
df.shape

(569, 33)

In [98]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [99]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


# Train test split

In [100]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [101]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(x_test)

In [102]:
X_train

array([[-1.0979381 , -1.00091766, -1.10408228, ..., -1.34783608,
         1.08667105, -0.22603762],
       [-0.73006691, -1.06891632, -0.72294996, ..., -0.61754123,
         0.05898524,  0.44408154],
       [ 1.38240556,  1.32745038,  1.46977215, ...,  2.01630658,
         2.94351247,  1.13730826],
       ...,
       [-1.30249678, -0.19431282, -1.29505219, ..., -0.97561449,
        -0.75348716, -0.1590257 ],
       [-0.45695041, -0.43113575, -0.46213271, ..., -0.15109776,
         0.21580742, -0.43342794],
       [ 0.53240015,  0.95931969,  0.43619296, ..., -0.23463313,
         0.07066348,  0.023524  ]], shape=(455, 30))

In [103]:
X_test

array([[-0.11688117,  0.11258652, -0.09057082, ...,  0.45100249,
        -0.2239871 ,  0.29094112],
       [-0.54708508, -0.15693104, -0.56229617, ..., -0.37776791,
         0.6109006 , -0.49426331],
       [-0.68356356, -0.26862301, -0.66467961, ..., -0.17678199,
        -0.69251058, -0.32965143],
       ...,
       [-0.25039273,  1.59857525, -0.31733745, ..., -0.82433299,
        -0.75239703, -0.88543163],
       [-0.81707512, -0.11565358, -0.74760174, ...,  0.1521328 ,
         0.76942358,  2.66031986],
       [-0.72510049, -0.64254827, -0.68287171, ..., -0.02655648,
        -0.14824834, -0.51892642]], shape=(114, 30))

In [104]:
y_train

60     B
478    B
42     M
231    B
85     M
      ..
563    M
343    M
359    B
497    B
10     M
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [105]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [106]:
y_train

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,

In [107]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0])

# Numpy arrays to PyTorch tensors

In [108]:
X_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [109]:
X_train_tensor.shape

torch.Size([455, 30])

In [110]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [111]:
class MyNN():

    def __init__(self,X):

        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self, X):
        z =torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):

        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

Important parameters

In [112]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [118]:
# Create a model
model = MyNN(X_train_tensor)

#define loop
for epoch in range(epochs):
# forward bias
  y_pred = model.forward(X_train_tensor)
  print(y_pred)
# loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
#backward bias 
  loss.backward()
#parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
# zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()
# print loss in each epoch
  print('Epoch:' ,{epoch + 1}, 'Loss:' ,{loss.item()})

tensor([[4.9080e-03],
        [2.7204e-03],
        [1.0000e+00],
        [2.3253e-05],
        [9.9916e-01],
        [1.0000e+00],
        [9.6284e-03],
        [9.9957e-01],
        [6.3670e-05],
        [1.3702e-02],
        [6.0333e-01],
        [1.9791e-05],
        [3.1652e-04],
        [3.4189e-03],
        [1.9811e-04],
        [2.0176e-05],
        [3.7852e-04],
        [9.9987e-01],
        [2.6069e-04],
        [9.5718e-01],
        [8.5910e-01],
        [8.3025e-04],
        [2.6062e-01],
        [7.4151e-05],
        [2.7748e-06],
        [2.9046e-01],
        [5.3222e-04],
        [1.0281e-04],
        [9.9832e-01],
        [2.4682e-03],
        [1.8554e-06],
        [9.9893e-01],
        [2.7876e-05],
        [7.0957e-02],
        [1.0000e+00],
        [9.9999e-01],
        [1.6514e-02],
        [7.5798e-01],
        [8.6490e-07],
        [9.1258e-01],
        [9.9996e-01],
        [9.9519e-01],
        [5.4366e-07],
        [1.0000e+00],
        [9.9994e-01],
        [4

In [119]:
model.bias

tensor([-0.1529], dtype=torch.float64, requires_grad=True)