In [1]:
import torch
print(torch.__version__)

2.7.1+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print("using gpu:",{torch.cuda.get_device_name(0)})
else:
    print("GPU not avaliable. using CPU")

GPU is available
using gpu: {'Quadro P3200'}


# Creating a Tensors

In [3]:
a = torch.empty(2,3)
type(a)

torch.Tensor

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(2,3)

tensor([[0.4444, 0.0969, 0.0039],
        [0.9054, 0.6700, 0.2600]])

In [7]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Tensors Shapes

In [9]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
x.shape

torch.Size([2, 3])

In [11]:
torch.empty_like(x)

tensor([[2265914147824,             0,             0],
        [            0,             0,             0]])

In [12]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [14]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensors Data Types

In [15]:
x.dtype

torch.int64

In [16]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [17]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [18]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

In [19]:
x =torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [20]:
x + 2
x - 2
x * 2
x / 2
x % 2
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [21]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [22]:
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [23]:
a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [24]:
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [25]:
a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [26]:
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [27]:
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [28]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [29]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [30]:
torch.negative(c)

tensor([-1,  2, -3,  4])

In [31]:
d = torch.tensor([1.0,2.3,2.5,3.2,5.2])

In [32]:
torch.round(d)

tensor([1., 2., 2., 3., 5.])

In [33]:
torch.ceil(d)

tensor([1., 3., 3., 4., 6.])

In [34]:
torch.floor(d)

tensor([1., 2., 2., 3., 5.])

In [35]:
torch.clamp(d, min=2,max=3)

tensor([2.0000, 2.3000, 2.5000, 3.0000, 3.0000])

In [36]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [37]:
torch.sum(e)

tensor(24.)

In [38]:
torch.sum(e, dim=1)

tensor([15.,  9.])

In [39]:
torch.sum(e,dim=0)

tensor([ 8.,  0., 16.])

In [40]:
torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [41]:
torch.mean(e,dim=1)

tensor([5., 3.])

In [42]:
torch.median(e)

tensor(0.)

In [43]:
torch.median(e,dim=0)

torch.return_types.median(
values=tensor([0., 0., 7.]),
indices=tensor([1, 0, 0]))

In [44]:
torch.median(e,dim=1)

torch.return_types.median(
values=tensor([7., 0.]),
indices=tensor([2, 1]))

In [45]:
torch.mode(e)

torch.return_types.mode(
values=tensor([0., 0.]),
indices=tensor([1, 1]))

In [46]:
torch.mode(e,dim=0)

torch.return_types.mode(
values=tensor([0., 0., 7.]),
indices=tensor([1, 1, 0]))

In [47]:
torch.mode(e,dim=1)

torch.return_types.mode(
values=tensor([0., 0.]),
indices=tensor([1, 1]))

In [48]:
torch.max(e)
torch.min(e)

tensor(0.)

In [49]:
torch.prod(e)

tensor(0.)

In [50]:
torch.std(e)

tensor(4.4272)

In [51]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [52]:
torch.log(k)

tensor([[1.6094, 1.9459, 1.0986],
        [2.1972, 1.3863,   -inf]])

In [53]:
torch.exp(k)

tensor([[1.4841e+02, 1.0966e+03, 2.0086e+01],
        [8.1031e+03, 5.4598e+01, 1.0000e+00]])

In [54]:
torch.relu(k)

tensor([[5., 7., 3.],
        [9., 4., 0.]])

# Inplace Operations

In [55]:
n = torch.rand(2,3)
m = torch.rand(2,3)

print(n)
print(m)

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])
tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])


In [56]:
m + n

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [57]:
m.add_(n)

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [58]:
m

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [59]:
torch.relu(m)

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [60]:
m.relu_()

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [61]:
m

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

# Copying a Tensors

In [62]:
a = torch.rand(2,3)
a

tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [63]:
b = a
b

tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [64]:
a[0][0] = 0
a

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [65]:
b

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [66]:
id(a)

2915541246064

In [67]:
id(b)

2915541246064

In [68]:
b = a.clone()

In [69]:
a

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [70]:
b

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [71]:
id(a)

2915541246064

In [72]:
id(b)

2915023642976

In [73]:
a[0][0] = 10
a

tensor([[10.0000,  0.3389,  0.6211],
        [ 0.5530,  0.6896,  0.3687]])

In [74]:
b

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [75]:
id(a)

2915541246064

In [76]:
id(b)

2915023642976

# Tensors Operations on GPU

In [77]:
torch.cuda.is_available()

True

In [78]:
device = torch.device('cuda')

In [79]:
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [80]:
a = torch.rand(2,3)
a

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]])

In [81]:
b = a.to(device)
b

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]], device='cuda:0')

In [82]:
b + 5

tensor([[5.9053, 5.8356, 5.3039],
        [5.6726, 5.5740, 5.9233]], device='cuda:0')

In [83]:
import torch
import time

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time


print(f"Time on CPU:{cpu_time:.4f} seconds")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu2,matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU:{gpu_time:.4f} seconds")

print("\nspeedup (CPU time / GPU time):",cpu_time / gpu_time)

Time on CPU:7.0120 seconds
Time on GPU:0.6492 seconds

speedup (CPU time / GPU time): 10.801533420914712


# Reshaping Tensors

In [84]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [85]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [86]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
b = torch.rand(2,3,4)
b

tensor([[[0.4455, 0.4799, 0.3206, 0.2995],
         [0.3521, 0.5425, 0.0926, 0.6088],
         [0.4722, 0.7327, 0.9103, 0.3328]],

        [[0.2774, 0.8399, 0.9186, 0.5959],
         [0.5539, 0.3423, 0.1570, 0.2660],
         [0.3715, 0.6096, 0.5115, 0.0678]]])

In [88]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [89]:
c = torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [90]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy & PyTorch

In [91]:
import numpy as np

In [92]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [93]:
b = a.numpy()
type(b)

numpy.ndarray

In [94]:
type(a)

torch.Tensor

In [95]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [96]:
type(c)

numpy.ndarray

In [97]:
torch.from_numpy(c)

tensor([1, 2, 3])